// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: scraper.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeResult_Status int32

const (
	ScrapeResult_UNKNOWN ScrapeResult_Status = 0
	ScrapeResult_SUCCESS ScrapeResult_Status = 1
	ScrapeResult_FAILURE ScrapeResult_Status = 2
)

// Enum value maps for ScrapeResult_Status.
var (
	ScrapeResult_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILURE",
	}
	ScrapeResult_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAILURE": 2,
	}
)

func (x ScrapeResult_Status) Enum() *ScrapeResult_Status {
	p := new(ScrapeResult_Status)
	*p = x
	return p
}

func (x ScrapeResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScrapeResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_scraper_proto_enumTypes[0].Descriptor()
}

func (ScrapeResult_Status) Type() protoreflect.EnumType {
	return &file_scraper_proto_enumTypes[0]
}

func (x ScrapeResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScrapeResult_Status.Descriptor instead.
func (ScrapeResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1, 0}
}

// ScrapeJob represents a job to be scraped by the Scraper service.
type ScrapeJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Used for tracing and linking requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeJob) Reset() {
	*x = ScrapeJob{}
	mi := &file_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeJob) ProtoMessage() {}

func (x *ScrapeJob) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeJob.ProtoReflect.Descriptor instead.
func (*ScrapeJob) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScrapeJob) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScrapeJob) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *ScrapeJob) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// ScrapeResult represents the outcome of a scraping job.
type ScrapeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        ScrapeResult_Status    `protobuf:"varint,2,opt,name=status,proto3,enum=v1.ScrapeResult_Status" json:"status,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                     // The scraped content, e.g., HTML or JSON
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Populated if status is FAILURE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResult) Reset() {
	*x = ScrapeResult{}
	mi := &file_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResult) ProtoMessage() {}

func (x *ScrapeResult) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResult.ProtoReflect.Descriptor instead.
func (*ScrapeResult) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScrapeResult) GetStatus() ScrapeResult_Status {
	if x != nil {
		return x.Status
	}
	return ScrapeResult_UNKNOWN
}

func (x *ScrapeResult) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ScrapeResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_scraper_proto protoreflect.FileDescriptor

const file_scraper_proto_rawDesc = "" +
	"\n" +
	"\rscraper.proto\x12\x02v1\"|\n" +
	"\tScrapeJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xc0\x01\n" +
	"\fScrapeResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.v1.ScrapeResult.StatusR\x06status\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"/\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x022\x10\n" +
	"\x0eScraperServiceB\x0fZ\rSkyEye/api/v1b\x06proto3"

var (
	file_scraper_proto_rawDescOnce sync.Once
	file_scraper_proto_rawDescData []byte
)

func file_scraper_proto_rawDescGZIP() []byte {
	file_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)))
	})
	return file_scraper_proto_rawDescData
}

var file_scraper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scraper_proto_goTypes = []any{
	(ScrapeResult_Status)(0), // 0: v1.ScrapeResult.Status
	(*ScrapeJob)(nil),        // 1: v1.ScrapeJob
	(*ScrapeResult)(nil),     // 2: v1.ScrapeResult
}
var file_scraper_proto_depIdxs = []int32{
	0, // 0: v1.ScrapeResult.status:type_name -> v1.ScrapeResult.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scraper_proto_init() }
func file_scraper_proto_init() {
	if File_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_proto_depIdxs,
		EnumInfos:         file_scraper_proto_enumTypes,
		MessageInfos:      file_scraper_proto_msgTypes,
	}.Build()
	File_scraper_proto = out.File
	file_scraper_proto_goTypes = nil
	file_scraper_proto_depIdxs = nil
}
